name: Build, Scan and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-scan-push:
    runs-on: ubuntu-latest
    name: Build, Scan and Push Docker Image

    steps:
      # 1. Checkout del código
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # 3. Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t arnaldoquezada/laboratorio-final:latest .

      # 4. Run Trivy Vulnerability Scanner and Save Report
      - name: Run Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@0.31.3
        with:
          image-ref: "arnaldoquezada/laboratorio-final:latest"
          format: "template"
          template: "@/contrib/html.tpl"
          output: "trivy-report.html" # Genera el archivo HTML
          severity: "CRITICAL,HIGH,MEDIUM"

      # 5. Upload Report as an Artifact
      - name: Upload Trivy Report
        uses: actions/upload-artifact@v3
        with:
          name: trivy-report
          path: trivy-report.html
      # 6. Push Docker Image (solo si no hay vulnerabilidades críticas, altas o medias)
      - name: Push Docker Image
        if: ${{ success() }} # Solo ejecutar si los pasos anteriores son exitosos
        run: |
          docker push arnaldoquezada/laboratorio-final:latest
