name: Build, Scan, and Push Docker Image

on:
  workflow_call:
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_TOKEN:
        required: true
jobs:
  build-and-scan:
    name: Build Scan and Upload
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # 3. Build Docker image
      - name: Build Docker Image
        run: |
          docker build -t arnaldoquezada/laboratorio-final:${{ github.sha }} .

      # 4. Run Trivy Vulnerability Scanner and Save Report
      - name: Run Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@0.29.0
        with:
          image-ref: "arnaldoquezada/laboratorio-final:latest"
          format: "template"
          template: "@/contrib/html.tpl"
          output: "trivy-report.html" # Genera el archivo HTML
          severity: "CRITICAL,HIGH,MEDIUM"

      # 5. Upload Report as an Artifact
      - name: Upload Trivy Report
        uses: actions/upload-artifact@v3
        with:
          name: trivy-report
          path: trivy-report.html

      # 6. Push Docker image (only if Trivy scan passes)
      - name: Push Docker Image
        if: success() # Este paso solo se ejecuta si el análisis de Trivy pasa
        run: |
          docker push arnaldoquezada/laboratorio-final:${{ github.sha }}
