name: SCA

on:
  workflow_call:

jobs:
  depchecktest:
    runs-on: ubuntu-latest
    name: Dependency-Check
    continue-on-error: true # Permite que el pipeline siga con otros jobs

    steps:
      # 1. Checkout del código
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Instalar dependencias del proyecto
      - name: Build project
        run: |
          npm install

      # 3. Ejecutar Dependency-Check
      - name: Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        id: depcheck
        env:
          JAVA_HOME: /opt/jdk
        with:
          project: "${{ github.event.repository.name }}"
          path: "."
          format: "HTML"
          out: "reports" # Directorio para guardar el reporte
          args: >
            --failOnCVSS 7
            --enableRetired

      # 4. Subir el reporte como artefacto (siempre)
      - name: Upload Dependency-Check Report
        if: always() # Este paso siempre se ejecutará
        uses: actions/upload-artifact@v3
        with:
          name: Dependency-Check Report
          path: ./reports/dependency-check-report.html

      # 5. Validar Vulnerabilidades
      - name: Validate Vulnerabilities
        run: |
          if grep -q "CRITICAL" ./reports/dependency-check-report.html || grep -q "HIGH" ./reports/dependency-check-report.html || grep -q "MEDIUM" ./reports/dependency-check-report.html; then
            echo "Vulnerabilities detected (CRITICAL, HIGH, MEDIUM)."
            exit 1 # Marca el job como fallido
          else
            echo "No critical vulnerabilities found."
          fi
