on:
  workflow_call:

jobs:
  depchecktest:
    runs-on: ubuntu-latest
    name: Dependency-Check
    steps:
      # 1. Checkout del código
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Instalar dependencias del proyecto
      - name: Install dependencies
        run: npm install

      # 3. Ejecutar Dependency-Check (No detener el pipeline si falla)
      - name: Run Dependency-Check
        run: |
          dependency-check.sh --project "laboratorio-final" \
            --scan "." \
            --format "HTML" \
            --out "reports" \
            --failOnCVSS 7 || echo "Dependency-Check failed, continuing pipeline"

      # 4. Subir el informe como artefacto
      - name: Upload Test results
        uses: actions/upload-artifact@v3
        with:
          name: Depcheck Report
          path: ./reports/dependency-check-report.html
