name: Dependency Analysis SCA

on:
  workflow_call:

jobs:
  depchecktest:
    runs-on: ubuntu-latest
    name: dependency-check
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build project
        run: |
          npm install
      - name: Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        env:
          JAVA_HOME: /opt/jdk
        with:
          project: "${{ github.event.repository.name }}"
          path: "."
          format: "HTML"
          out: "reports" # this is the default, no need to specify unless you wish to override it
          args: >
            --failOnCVSS 7
            --enableRetired
      - name: Upload Test results
        uses: actions/upload-artifact@v3
        with:
          name: Depcheck report
          path: reports/dependency-check-report.html
