name: SonarCloud Analysis

on:
  workflow_call:

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Configurar Java a la versión 17
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # 3. Instalar SonarScanner CLI
      - name: Install SonarScanner CLI
        run: |
          curl -sSLo sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
          unzip sonar-scanner-cli.zip
          mv sonar-scanner-4.7.0.2747-linux sonar-scanner
          echo "SONAR_SCANNER_HOME=$PWD/sonar-scanner" >> $GITHUB_ENV
          echo "PATH=$PATH:$PWD/sonar-scanner/bin" >> $GITHUB_ENV

      # 4. Verificar la versión de Java y SonarScanner
      - name: Verify Java and SonarScanner Versions
        run: |
          java -version
          sonar-scanner --version
        env:
          JAVA_HOME: /opt/hostedtoolcache/jdk/17.0.13/x64

      # 5. Ejecutar SonarScanner
      - name: Run SonarScanner
        run: |
          sonar-scanner \
            -Dsonar.projectKey=arnaldoquezada-personal_laboratorio-final \
            -Dsonar.organization=arnaldoquezada-personal \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.sources=. \
            -X
        env:
          JAVA_HOME: /opt/hostedtoolcache/jdk/17.0.13/x64
          PATH: /opt/hostedtoolcache/jdk/17.0.13/x64/bin:$PATH
