name: SonarCloud Analysis

on:
  workflow_call:

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Configurar Java
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      # 3. Instalar SonarScanner CLI
      - name: Install SonarScanner CLI
        run: |
          curl -sSLo sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
          unzip sonar-scanner-cli.zip
          mv sonar-scanner-4.7.0.2747-linux sonar-scanner
          export PATH=$PATH:$PWD/sonar-scanner/bin

      # 4. Ejecutar SonarScanner con `-X` para depuración
      - name: SonarCloud Scan with Debug
        run: |
          sonar-scanner \
            -Dsonar.projectKey=arnaldoquezada-personal_laboratorio-final \
            -Dsonar.organization=arnaldoquezada-personal \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.toke=$SONAR_TOKEN \
            -Dsonar.sources=. \
            -X
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          REPO_NAME: ${{ github.event.repository.name }}
