name: SonarCloud Analysis
on:
  workflow_call:

jobs:
  sonarCloudTrigger:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: SonarCloud Scan
        uses: sonarsource/sonarqube-scan-action@v2
        with:
          args: >
            -Dsonar.projectKey=arnaldoquezada_laboratorio-final
            -Dsonar.organization=arnaldoquezada-personal
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.sources=.
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
